name: CI
'on':
  push:
    branches:
      - master
      - develop
  workflow_dispatch:

jobs:
  build-dita:
    name: Build DITA
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v6

      - name: Build Bootstrap Component
        uses: dita-ot/dita-ot-action@4.4
        with:
          install: |
            mkdir -p dtd/base
            curl -L https://raw.githubusercontent.com/dita-bootstrap/dita-bootstrap.specialization/master/dtd/base/bootstrapDomain.ent -o dtd/base/bootstrapDomain.ent
            curl -L https://raw.githubusercontent.com/dita-bootstrap/dita-bootstrap.specialization/master/dtd/base/bootstrapDomain.mod -o dtd/base/bootstrapDomain.mod
            curl -L https://raw.githubusercontent.com/dita-bootstrap/dita-bootstrap.specialization/master/dtd/base/commonElements.mod -o dtd/base/commonElements.mod
          plugins: |
            fox.jason.extend.css
            https://github.com/dita-bootstrap/dita-bootstrap.html/archive/develop.zip
            https://github.com/dita-bootstrap/dita-bootstrap.specialization/archive/develop.zip
            https://github.com/dita-bootstrap/com.example.bootstrap-component/archive/master.zip
          project: .github/dita-ot/html.xml

